# docker-compose.yaml for Mautic 6 with AWS SES
version: "3.8"

services:
  database:
    image: percona/percona-server:8.0
    container_name: mautic_db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:?required}
      - MYSQL_DATABASE=${MYSQL_DATABASE:?required}
      - MYSQL_USER=${MYSQL_USER:?required}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:?required}
    volumes:
      - db_data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    networks:
      - mautic-net
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "127.0.0.1",
          "-uroot",
          "-p$${MYSQL_ROOT_PASSWORD}",
        ]
      start_period: 60s
      interval: 5s
      timeout: 3s
      retries: 30

  mautic:
    build: .
    container_name: mautic_app
    restart: always
    depends_on:
      database:
        condition: service_healthy
    #    ports:
    #      - "8080:80"
    environment:
      - MAUTIC_DB_HOST=database
      - MAUTIC_DB_USER=${MYSQL_USER:?required}
      - MAUTIC_DB_PASSWORD=${MYSQL_PASSWORD:?required}
      - MAUTIC_DB_NAME=${MYSQL_DATABASE:?required}
      - MAUTIC_SITE_URL=${MAUTIC_SITE_URL:?required}
      - MAUTIC_RUN_CRON_JOBS=false
      - MAUTIC_TRUSTED_PROXIES=["0.0.0.0/0"]
      - PHP_INI_MEMORY_LIMIT=512M
      - PHP_INI_MAX_EXECUTION_TIME=300
      - APP_ENV=prod
      - APP_SECRET=${APP_SECRET:?required}
    volumes:
      # Persist important data directories
      - mautic_config:/var/www/html/config
      - mautic_media:/var/www/html/docroot/media
      - mautic_logs:/var/www/html/var/logs
      - mautic_cache:/var/www/html/var/cache
    networks:
      - mautic-net

volumes:
  db_data:
    driver: local
  mautic_config:
    driver: local
  mautic_media:
    driver: local
  mautic_logs:
    driver: local
  mautic_cache:
    driver: local

networks:
  mautic-net:
    driver: bridge
